### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by brsbilgin** [SnappyRobotics/snappy-ros#10]
After installation of snappy-ros packages it gives this error. I tried it with different version of node-red.  I couldn't find what breakdown this package. It was working well. 
2 Sep 10:04:19 - [info]  - snappy-ros:ros-subscriber : TypeError: Cannot read property 'split' of undefined
2 Sep 10:04:19 - [info]  - snappy-ros:ros-publisher : TypeError: Cannot read property 'split' of undefined

**Comment by mirkosertic** [comment]
I got this error when ROS message definitions were missing. Are you sure you've got a valid ROS installation?

**Comment by brsbilgin** [comment]
The issue was missing workspace. Thank you for support.
