### ISSUE TITLE
Not working when running on Ubuntu Mate (Raspberry Pi)

### ISSUE THREAD

**Issue by Kreativadelar** [SnappyRobotics/snappy-ros#6]
Hello

I'm trying to get subscriptions to work but something is not working as expected.

When I add a Subscribe node the data packagetype is empty and also the datatype combo boxes. What am I doing wrong. The robot/ROS is working fine, are there any dependencies for rosnodejs except running Kinteic version of ROS? 

I'm running node version 4.2.6 if that could be a problem
pabi@pabi-desktop:~/.node-red$ node -v
v4.2.6

[ERROR] [1497473691.086] (ros.rosnodejs): Exception trying to subscribe to topic /left_rpm
[INFO] [1497473691.691] (ros): Connected to master at http://localhost:11311!
[WARN] [1497473691.703] (ros): Unable to setup ros logging stream
[WARN] [1497473691.711] (ros): Unable to setup ros logging services
[ERROR] [1497473691.779] (ros.rosnodejs): Exception trying to subscribe to topic /rgb

I haven't used rosnodejs but I guess it need to generate the message types in some way?

**Comment by prajankya** [comment]
This issue occurs when there are no messages generated by gennodejs. Gennodejs is run by message_generation package, which is inbuilt in ROS, and generates .js datatypes when installed.


few things you can do are ..

- Install message_generation package if not install(but its very unlikely)
- Install gennodejs package, or reinstall( look for not corrupting your ROS installation)
- Check if messages are generated(In my PC its at `/opt/ros/kinetic/share/gennodejs/ros`)

If non of the above methods work, as a hack, you can copy the specific folder of your package from your PC and put it at the same place in PI. (for example if you need `std_msgs` then copy  `/opt/ros/kinetic/share/gennodejs/ros/std_msgs/` from a PC with working ROS setup to your RPi at the same location(or different depending on your ROS install location).

Remember, this hack only works for the packages which are installed on RPi, (for example, for using gazebo_msgs, you need to install `gazebo_msgs` package in RPi, and then copy the package msgs generated folder as described above)

This is issue is  not a part of this repo(snappy-ros) its a problem with ROS I guess on ARM, as I faced the same problem with another ARM board(having OpenEmbedded Yocto Linux) and did the same hack at last.


If you get any other way of solving this issue, please let us know.

Hope this helps.

**Comment by prajankya** [comment]
I am closing this as there is no update from you.!

**Comment by PatrikBichis** [comment]
Sorry yes it is working when running it on PC, I haven't gotten the time to test it on the RPi. So as you say it's not a problem with the snappy-ros node.

**Comment by prajankya** [comment]
yes, Its the problem of the install on RPi, I have given some solutions for that as well.
