### ISSUE TITLE
Can not output complete topic msg.

### ISSUE THREAD

**Issue by HowardWhile** [SnappyRobotics/snappy-ros#7]
Hi
When I subscribing topic like [std_msgs/Int32MultiArray](http://docs.ros.org/api/std_msgs/html/msg/Int32MultiArray.html). 

> std_msgs/MultiArrayLayout layout
int32[] data

The node only output` int32[] data` .
Lost contents of layout.

**Comment by prajankya** [comment]
I suppose you are using subscriber node,

Can you tell which node in ros is sending the `std_msgs/Int32MultiArray` msg ? so I can test for it.

**Comment by HowardWhile** [comment]
Use this ros command to pub latching std_msgs/Int32MultiArray message

> rostopic pub /array_test std_msgs/Int32MultiArray "{layout: {dim:[{label: 'hi', size: 0, stride: 0}], data_offset: 0}, data:[4,5,6]}"

and subscribe by this node red flow

> [{"id":"af9d3372.eeb07","type":"ros-subscriber","z":"bdb2cb0.698d738","topicname":"/array_test","typepackage":"std_msgs","typename":"Int32MultiArray","x":160,"y":460,"wires":[["f085d33e.6145a"]]},{"id":"f085d33e.6145a","type":"debug","z":"bdb2cb0.698d738","name":"","active":false,"console":"false","complete":"true","x":310,"y":460,"wires":[]}]

**Comment by prajankya** [comment]
Cool, I thought you were using a node, anyways, I will get back to you asap(in an hour or two), with the solution.

And congrats for joining github, I see this is your first contribution !

**Comment by HowardWhile** [comment]
Yeah, I am a beginner on github. 
Thank you so much for responding to my issue.

**Comment by prajankya** [comment]
This issue is solved in the latest patch, you need to update(better reinstall) this package `snappy-ros`.

Hope you got what you needed.
