### ISSUE TITLE
When sending topic, receive an incorrect message. Related to issue #7

### ISSUE THREAD

**Issue by HowardWhile** [SnappyRobotics/snappy-ros#8]
Hello,

I got some troubles when sending topic by publisher node.

Use this node-red example
`[{"id":"ae61e4d1.67f2d8","type":"ros-publisher","z":"188aa311.be25ed","topicname":"/test_array2","typepackage":"sensor_msgs","typename":"LaserEcho","x":430,"y":640,"wires":[]},{"id":"ce3405fe.1b8e68","type":"ros-subscriber","z":"188aa311.be25ed","topicname":"/test_array2","typepackage":"sensor_msgs","typename":"LaserEcho","x":250,"y":720,"wires":[["be611075.10172"]]},{"id":"be611075.10172","type":"debug","z":"188aa311.be25ed","name":"","active":true,"console":"false","complete":"false","x":430,"y":720,"wires":[]},{"id":"bcb1fbbc.5d7c78","type":"inject","z":"188aa311.be25ed","name":"","topic":"","payload":"{\"echoes\":[1.1,2,3]}","payloadType":"json","repeat":"","crontab":"","once":false,"x":230,"y":640,"wires":[["ae61e4d1.67f2d8"]]}]`

When I am sending topic [sensor_msgs/LaserEcho](http://docs.ros.org/api/sensor_msgs/html/msg/LaserEcho.html)

Whether subscribe by `node-red subscriber node` or command line `rostopic echo /test_array2`,
I will get empty array `array[0]`

```
In the file /ros-publisher/ros-publisher.js    

node.on('input', function(msg) {
    var msgType = rosnodejs.require(config.typepackage).msg[config.typename]

    var x = new msgType()
    x.data = msg.payload <<----

    node.pub.publish(x)
})
```
I think the problem should be caused by this part of the program?

**Comment by HowardWhile** [comment]
I try to solve this problem in this [branch](https://github.com/makubex49/snappy-ros/tree/publishe_array_msg)

But I found that when sending the wrong json into the publisher node.
It can make node-red crash.
I have no idea to protect this situation.

**Comment by prajankya** [comment]
Actually the core problem is ros uses `data` is few data types(I had not thought of it previously, other that this, the package is well tested) and node-red also uses `data` just to use as data. I have a solution, and would take a bit of time as I would have to change a lot of things, even the documentation(Guess some couple of hours, but its mid-night here now, will be able to send you in some 8-10 hours). Hope you hang on tight, I would send the working version asap.!

**Comment by prajankya** [comment]
Now I am definite that the issue is solved, I tested with most of the datatypes in standard ROS, and with the given flows you tried to test with. Its working as expected. Hope its working for you as well !

**Comment by HowardWhile** [comment]
It is working, thanks a lot!

**Comment by HowardWhile** [comment]
But after this change, we cannot use this [tutorial](https://github.com/SnappyRobotics/snappy-ros#publisher).
This will cause node-red crash.

It must send payload with complete topic type.
```
msg.payload = {
  data:"Hello World"
};
```
Is it possible add some exception handling to protect this situation?

**Comment by prajankya** [comment]
Yes, the tutorial would not work now. As I said, I need to update the documentation as well. And actually it is better for a library to have uniform code everywhere.
For having data to be printed out, it would be difficult to maintain integrity of the message, and hence its better to print whole object, as shown in the `Edit pane` which is showing whole `Object` with `data` as a parameter.

It is possible, but __Inconsistent__ throughout the library.

You can easily use in the method you want by just putting a function node, and giving something similar to 

```javascript
msg.payload = msg.payload.data;
```

**Comment by HowardWhile** [comment]
Yes, I agree with you.
Putting a function node is a simple solution.
Thanks for your reminder.
